### ISSUE TITLE
Provide a generated docset

### ISSUE THREAD

**Issue by mattijsbliek** [riiid/rxjs-dash#2]
I was wondering whether you could provide a generated docset in this repo. This would prevent people from having to build it themselves.

P.s. I'm new to Dash docsets, so I don't know what is considered best practice here.

**Comment by agzam** [comment]
Yes, I am curious as well. Could this be published?

**Comment by chitacan** [comment]
Sorry for the late response. @mattijsbliek you can find generated docset on [release](https://github.com/riiid/rxjs-dash/releases) page.

@agzam I'm sure I will publish this docset to main dash repo soon.
