### ISSUE TITLE
Why this isn't part of Dash's default library?

### ISSUE THREAD

**Issue by rafaelbiten** [riiid/rxjs-dash#5]
Thanks a lot for this documentation. Works great!

A couple of questions. When v5 is released and we have docs for it, I think we'd have to do the same process again, right?

Any reason why this isn't part of Dash by default?

Thanks again!

**Comment by chitacan** [comment]
Well, I'm preparing major rewrite for this project. It includes

* use es6 (dump coffeescript).
* add test.
* remove git submodule dependency.

after that, I'll consider to submit as docset.

For v5, It has completely different doc structure. We need to update [script](https://github.com/riiid/rxjs-dash/blob/master/docset.coffee) to support v5 documentation.
